### ISSUE TITLE
MEDM screen features

### ISSUE THREAD

**Issue by decarlof** [xray-imaging/tomostream#2]
Add to tomoScan missing streaming specific PVs:

- streaming Start/Stop
- streaming Save
- streaming Center

anything else?

**Comment by decarlof** [comment]
- binnning
- ring removal on/off
- paganin on/off alfa

**Comment by decarlof** [comment]
- buffer size

**Comment by nikitinvv** [comment]
- rotation center

**Comment by nikitinvv** [comment]
- filter type: parzen, shepp-logan, ramp, butterworth

**Comment by decarlof** [comment]
Added:

2bma:TomoScan:Stream
2bma:TomoScan:StreamBufferSize
2bma:TomoScan:StreamSave
2bma:TomoScan:StreamBinning
2bma:TomoScan:StreamRingRemoval
2bma:TomoScan:StreamPaganin
2bma:TomoScan:StreamPaganinAlpha
2bma:TomoScan:StreamCenter
2bma:TomoScan:StreamFilterType

Renamed the X-Y-Z slider PVs as:

2bma:TomoScan:StreamOrthoX
2bma:TomoScan:StreamOrthoY
2bma:TomoScan:StreamOrthoZ

Updated medm screen to access the new PVs
<img width="447" alt="Screen Shot 2020-07-20 at 6 02 11 PM" src="https://user-images.githubusercontent.com/5884150/87994677-2c55d200-cab3-11ea-9066-f2cbe9eef32f.png">

**Comment by decarlof** [comment]
Let's keep it open for other medm screen changes. All above request are addressed and screen now is:
![Screen Shot 2020-07-31 at 5 07 18 PM](https://user-images.githubusercontent.com/5884150/89081171-65623200-d350-11ea-92cc-78ef1ea5c01f.png)
